[package]
name = "xwin"
version = "0.1.0"
edition = "2024"

[features]
default = ["tracing"]

[build-dependencies]
cmake = "0.1"
bindgen = "0.72"
xela_build = { path = "../../xbuild" }

[dependencies]
tracing = { version = "0.1.44", optional = true }
linkme = "0.3"
xwin_macro = { path = "../xwin_macro" }