[package]
name = "xwin"
version = "0.1.0"
edition = "2024"

[features]
default = []
glfw = []
bindings = ["glfw"]
vulkan = ["glfw"]

[dependencies]
xela_channels = { git = "https://github.com/XelaSpirit/xela_channels.git", branch = "master" }
tracing = { version = "0.1.44", optional = true }

[build-dependencies]
cmake = "0.1"
bindgen = "0.72"
xela_build = { git = "https://github.com/XelaSpirit/xela_build.git", branch = "master" }
