[package]
name = "xwin"
version = "0.1.0"
edition = "2024"

[features]
default = ["vulkan"]
vulkan = []

[build-dependencies]
cmake = "0.1"
bindgen = "0.72"
xela_build = { path = "../../xbuild" }

[dependencies]
xela_channels = { path = "../../xela_channels" }
tracing = { version = "0.1.44", optional = true }
